databases:
  - name: Practicadb
    plan: free
    databaseName: practica
    user: practica

services:
  - type: web
    plan: free
    name: Practica
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "waitress-serve --listen 127.0.0.1:8000 Practica.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Practicadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4  
